eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
            '[/**]':
                allowedOrigins: "http://localhost:4200/"
                allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
                allowedHeaders:
                - "*"
      routes:
#########################User#################################
        - id: user-api-public-0
          uri: lb://user-api
          predicates:
            - Path=/user/**,/token/**
            - Method=OPTIONS

        - id: user-api-public-1
          uri: lb://user-api
          predicates:
            - Path=/user/login,/token/**

        - id: user-api-private-1
          uri: lb://user-api
          predicates:
            - Path=/user/**
          filters:
            - JwtAuth
#########################Product#################################
        - id: product-api-public-0
          uri: lb://product-api
          predicates:
            - Path=/product/**
            - Method=OPTIONS

        - id: product-api-public-1
          uri: lb://product-api
          predicates:
            - Path=/product/**
            - Method=GET

        - id: product-api-private-1
          uri: lb://product-api
          predicates:
            - Path=/product/**
          filters:
            - JwtAuth
#########################Coupon#################################
        - id: coupon-api-public-0
          uri: lb://coupon-api
          predicates:
            - Path=/coupon/**,/consumption/**
            - Method=OPTIONS

        - id: coupon-api-private-1
          uri: lb://coupon-api
          predicates:
            - Path=/coupon
            - Method=GET
          filters:
            - JwtAuth

        - id: coupon-api-private-2
          uri: lb://coupon-api
          predicates:
            - Path=/coupon,/coupon/deactivation/**,/coupon/activation/**
            - Method=POST,PUT
          filters:
            - JwtAuth

        - id: coupon-api-private-3
          uri: lb://coupon-api
          predicates:
            - Path=/consumption/**
          filters:
            - JwtAuth

        - id: coupon-api-public
          uri: lb://coupon-api
          predicates:
            - Path=/coupon/**,/consumption/**
#########################Store#################################
        - id: store-api-public-0
          uri: lb://store-api
          predicates:
            - Path=/store/**,/consumption/**,/stock/**
            - Method=OPTIONS

        - id: store-api-private-1
          uri: lb://store-api
          predicates:
            - Path=/store/consumption/**
          filters:
            - JwtAuth

        - id: store-api-private-2
          uri: lb://store-api
          predicates:
            - Path=/store/**,/consumption/**,/stock/**
            - Method=POST
          filters:
            - JwtAuth

        - id: store-api-consume-public-1
          uri: lb://store-api
          predicates:
            - Path=/store/**,/consumption/**,/stock/**
#########################Order#################################
        - id: order-api-public-0
          uri: lb://order-api
          predicates:
            - Path=/order/**
            - Method=OPTIONS

        - id: order-api-private-1
          uri: lb://order-api
          predicates:
            - Path=/order/**
            - Method=GET
          filters:
            - JwtAuth

        - id: order-api-public-1
          uri: lb://order-api
          predicates:
            - Path=/order/**