eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
            '[/**]':
                allowedOrigins: "http://localhost:4200/"
                allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
                allowedHeaders:
                - "*"
      routes:
        - id: user-api-public
          uri: lb://user-api
          predicates:
            - Path=/user/login,/token/**

        - id: user-api-private
          uri: lb://user-api
          predicates:
            - Path=/user/**

        - id: product-api-public
          uri: lb://product-api
          predicates:
            - Path=/product/**
            - Method=GET

        - id: product-api-private
          uri: lb://product-api
          predicates:
            - Path=/product/**

        - id: store-api-public
          uri: lb://store-api
          predicates:
            - Path=/store/**
            - Method=GET

        - id: store-api-consume-public
          uri: lb://store-api
          predicates:
            - Path=/store/consumeProducts

        - id: store-api-private
          uri: lb://store-api
          predicates:
            - Path=/store/**

        - id: order-api-public
          uri: lb://order-api
          predicates:
            - Path=/order/**

        - id: coupon-api-public
          uri: lb://coupon-api
          predicates:
            - Path=/coupons/**

        - id: store-api-public
          uri: lb://store-api
          predicates:
            - Path=/store/**