spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
            '[/**]':
                allowedOrigins: "http://localhost:4200/"
                allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
                allowedHeaders:
                - "*"
      routes:
#########################User#################################
        - id: user-api-public-0
          uri: http://user-api
          predicates:
            - Path=/user/**,/token/**
            - Method=OPTIONS

        - id: user-api-public-1
          uri: http://user-api:8080
          predicates:
            - Path=/user/login,/token/**

        - id: user-api-private-1
          uri: http://user-api:8080
          predicates:
            - Path=/user/**
          filters:
            - JwtAuth
#########################Product#################################
        - id: product-api-public-0
          uri: http://product-api:8080
          predicates:
            - Path=/product/**
            - Method=OPTIONS

        - id: product-api-public-1
          uri: http://product-api:8080
          predicates:
            - Path=/product/**
            - Method=GET

        - id: product-api-private-1
          uri: http://product-api:8080
          predicates:
            - Path=/product/**
          filters:
            - JwtAuth
#########################Coupon#################################
        - id: coupon-api-public-0
          uri: http://coupon-api:8080
          predicates:
            - Path=/coupon/**,/consumption/**
            - Method=OPTIONS

        - id: coupon-api-private-1
          uri: http://coupon-api:8080
          predicates:
            - Path=/coupon
            - Method=GET
          filters:
            - JwtAuth

        - id: coupon-api-private-2
          uri: http://coupon-api:8080
          predicates:
            - Path=/coupon,/coupon/deactivation/**,/coupon/activation/**
            - Method=POST,PUT
          filters:
            - JwtAuth

        - id: coupon-api-private-3
          uri: http://coupon-api:8080
          predicates:
            - Path=/consumption/**
          filters:
            - JwtAuth

        - id: coupon-api-public
          uri: http://coupon-api:8080
          predicates:
            - Path=/coupon/**,/consumption/**
#########################Store#################################
        - id: store-api-public-0
          uri: http://store-api:8080
          predicates:
            - Path=/store/**,/consumption/**,/stock/**
            - Method=OPTIONS

        - id: store-api-private-1
          uri: http://store-api:8080
          predicates:
            - Path=/store/consumption/**
          filters:
            - JwtAuth

        - id: store-api-private-2
          uri: http://store-api:8080
          predicates:
            - Path=/store/**,/consumption/**,/stock/**
            - Method=POST
          filters:
            - JwtAuth

        - id: store-api-consume-public-1
          uri: http://store-api:8080
          predicates:
            - Path=/store/**,/consumption/**,/stock/**
#########################Order#################################
        - id: order-api-public-0
          uri: http://order-api:8080
          predicates:
            - Path=/order/**
            - Method=OPTIONS

        - id: order-api-private-1
          uri: http://order-api:8080
          predicates:
            - Path=/order/**
            - Method=GET
          filters:
            - JwtAuth

        - id: order-api-public-1
          uri: http://order-api:8080
          predicates:
            - Path=/order/**